### ISSUE TITLE
No map shown

### ISSUE THREAD

**Issue by woepwoep** [Treedent/rt_simpleosm#4]
I get the noValidMapRecordSelected error message in the backend (Page mode showing the Plugin settings) while i entered a valid OSM record and added this record in the Plugin settings.

In the front end, the map is not displayed, only a grey area with the usual + and - zoom keys.

What is wrong?

Typo3 v9.5.9

**Comment by woepwoep** [comment]
After some debugging:

In PageLayoutViewDrawItemHook.php upon entering line #105
`preg_match_all( '/tx_rtsimpleosm_domain_model_osm_(\d+),?/', $flexform['mapselection']['settings.MapRecord'], $mapRecords );
`
The $flexform['mapselection']['settings.MapRecord'] holds the value '1' (1 char)
and upon exiting this preg_match_all function, $mapRecords is an array of 2 arrays each of which is empty.

Hope this helps

**Comment by Treedent** [comment]
Thank you. I Will return near you if I need more details about your implementation.

**Comment by bergischweb** [comment]
Exactly the same with me: TYPO3 9.5.9 and rt_simpleosm 2.0.1

**Comment by christophmai** [comment]
Same problem here on TYPO3 9.5.9 and rt_simpleosm 2.0.1. Installation on TYPO3 7.6.32 seems to work fine.

**Comment by Treedent** [comment]
It's seems that there is a problem when saving plugin options within the flexform allowed types. 
To avoid the problem temporarily, try to add the prefix type 'tx_rtsimpleosm_domain_model_osm_' before the id of the selected map in the pi_flexform field in the database record.

FROM
 
```
<field index="settings.MapRecord">
   <value index="vDEF">23</value>
</field>
```

TO
```
<field index="settings.MapRecord">
   <value index="vDEF">tx_rtsimpleosm_domain_model_osm_23</value>
</field>
```

**Comment by christophmai** [comment]
Now the map is shown but no marker and address is shown

**Comment by Treedent** [comment]
I don't see this problem at all. Have you verify the plugin options ?

**Comment by imberg** [comment]
Same to me: TYPO3 9.5.9 and rt_simpleosm 2.0.1, php 7.3.6
Backend: ![grafik](https://user-images.githubusercontent.com/17158181/65755675-dc68e180-e113-11e9-96d2-4395f8cc0e8e.png)

Frontend: 
![grafik](https://user-images.githubusercontent.com/17158181/65755713-eee31b00-e113-11e9-8fb1-29b737142bb9.png)

I verified plugin options and also tried the same as in your user manual ... it always shows an error in the backend (see above)

**Comment by Treedent** [comment]
Got no time to correct this this month.
Just try to install tt_address extension
https://extensions.typo3.org/extension/tt_address/
Then deselect and reselect a map in the plugin, so the correct map type_id will be stored in the database, and the problem will goes away.
A new version will be done next month.
Thanks to try this tips and tell me if it works for you.

**Comment by bergischweb** [comment]
I made two patches, one in `OsmController.php`:

Replacing:
```
preg_match_all( '/tx_rtsimpleosm_domain_model_osm_(\d+),?/', $this->settings['MapRecord'], $mapRecords );
// (around line 85)
```
with:
```
$mapRecords = [];
$mapRecords[0] = explode(',', $this->settings['MapRecord']);
for($i=0;$i<count($mapRecords[0]);$i++) {
    $mapRecords[1][$i] = str_replace('tx_rtsimpleosm_domain_model_osm_', '', $mapRecords[0][$i]);
}
```

And similar in `PageLayoutViewDrawItemHook.php`:

Replacing:
```
preg_match_all('/tx_rtsimpleosm_domain_model_osm_(\d+),?/', $flexform['mapselection']['settings.MapRecord'], $mapRecords);
```

with:
```
$mapRecords = [];
$mapRecords[0] = explode(',', $flexform['mapselection']['settings.MapRecord']);
for($i=0;$i<count($mapRecords[0]);$i++) {
     $mapRecords[1][$i] = str_replace('tx_rtsimpleosm_domain_model_osm_', '', $mapRecords[0][$i]);
 }
```

Like this I am independent of any misfunction in the flexform. First, the record list of the flexform is exploded into an array. After this, the tx_rtosm... prefix is replaced in each record item. If there is no prefix, the record item remains unchanged.

I won't say, it is a solution, but it is a workaround. The question remains, why the table name is not prefixed to the record id.

**Comment by Treedent** [comment]
This extension provides 2 ways to get markers on the map.
1. From a simple OSM map record
2. From tt_address address record

The flexform, when managing 2 types (tt_address installed), add automatically the record prefix.
When managing just one type (Simple OSM), the prefix is not added.
The part of code managing records is by now incomplete.
So the tt_address integration is actually mandatory.
Will be corrected in the next version soon.

**Comment by bergischweb** [comment]
That's what I presumed. So you could make a distinction: 
IF tt_addess is not installed, you take my code. 
IF it is installed you take your code.

**Comment by epxfrho** [comment]
You can add `<prepend_tname>1</prepend_tname>` to the config of the field settings.MapRecord inside the file flexform_simpleosm.xml.

**Comment by Treedent** [comment]
Thanks for the tip epxfrho. I will implement this in the week.

**Comment by anderlk** [comment]
Hi, there,
is the bug already fixed on TER? I still see the problem in version 8.7.30.

**Comment by Cyasi** [comment]
Still have the issue with 9.5.14 and 9.5.15. No tt_addess installed. Patch of bergischweb works.

**Comment by Treedent** [comment]
Fixed with version 4.1.2
